[files]
extend-exclude = []
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = false
check-file = true
unicode=true
locale = "en"
extend-ignore-re = [
  '\*\*[a-zA-Z\s]+\*\*\S*', # Excludes "**C**ontrol" syntax
  '(?:[a-fA-F0-9]{2}:){15}[a-fA-F0-9]{2}\b', # ipv6 format
  '\b(?:[a-zA-Z][a-zA-Z-]*: )?[a-fA-F0-9][a-fA-F0-9-]{7,}\b', # matches hex IDs
  '\b[0-9a-fA-F]{8,}\b', # excludes hashes and other random strings
  '\b[A-Z][A-Z0-9]*\b', # excludes full caps words
  # '```.*$[\s\S]*```',  excludes code blocks
  '[a-zA-Z]+([A-Z][a-z]+)+' # excludes Camel case and other funny upper/lower cases
]
extend-ignore-identifiers-re = []
extend-ignore-words-re = []

[default.extend-words]
pn = "pn"
mosquitto = "mosquitto"
Aer = "Aer"
aer = "aer"
AER = "AER"
ND = "ND"
thi = "thi"
fo = "fo"
vertx = "vertx"
Uncorrect = "Uncorrect"
Unexpect = "Unexpect"
Interfac = "Interfac"
Timestmp = "Timestmp"
informations = "informations"
Transfert = "Transfert"