blank_issues_enabled: false
contact_links:
  - name: Scaleway assistance
    url: https://console.scaleway.com/support/tickets/
    about: Contact Scaleway Assistance for help with product-related issues.
